language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

script:
# - npm test
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dwm-xt
    local_dir: build/
    skip_cleanup: true
    acl: public_read
    region: "us-east-1"
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dwm-staging
    local_dir: build/
    skip_cleanup: true
    acl: public_read
    region: "us-east-1"
    on:
      branch: develop
